version: '2'
services:
  compiler:
    build: .
    image: compiler:latest
    volumes:
      - ../package:/var/task
    environment:
      DEBUG=*
      SLS_DEBUG=*
    command: [npm, install, --production]
